version: '3.4'

services:
  meetupproject.identityserver:
    container_name: identity
    image: ${DOCKER_REGISTRY-}meetupprojectidentityserver
    environment: 
        IDENTITY_SERVER_DATABASE_CONNECTION_STRING: "Host=postgres-database;Database=identityDb;Username=postgres;Password=root"
        ASP_NET_IDENTITY_DATABASE_CONNECTION_STRING: "Host=postgres-database;Database=AspIndetityDb;Username=postgres;Password=root"
    ports:
        - "5000:80"
    build:
      context: .
      dockerfile: MeetupProject.IdentityServer/Dockerfile

  meetupproject.api:
    image: ${DOCKER_REGISTRY-}meetupprojectapi
    container_name: api
    environment: 
        EVENTS_DATABASE_CONNECTION_STRING: "Host=localhost;Port=5432;Database=events;Username=postgres;Password=root"
    build:
      context: .
      dockerfile: MeetupProject.API/Dockerfile

  postgres:
    container_name: postgres-database
    image: postgres:latest
    user: root
    environment:
      POSTGRES_DB: "identityDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: postgres-admin
    image: dpage/pgadmin4:latest
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgadmin-data:
  postgres-data:
    driver: local